version: 0.2
env:
  secrets-manager:
    SPICEDB_TOKEN: spicedb/credentials:SecretString:spicedb_token:AWSCURRENT
    SPICEDB_PASSWORD: spicedb/credentials:SecretString:postgres_spicedb_password:AWSCURRENT
    SPICEDB_USERNAME: spicedb/credentials:SecretString:postgres_spicedb_username:AWSCURRENT
  parameter-store:
    SPICEDB_HOSTNAME: "/SpiceDbHostname"
    SPICEDB_DATABASE_NAME: "/SpiceDbDatabaseName"
    SPICEDB_SERVICE_ADDRESS: "/SpiceDbServiceAddress"
proxy:
  upload-artifacts: no
  logs: no
phases:
  install:
    runtime-versions:
      golang: 1.20
    commands:
      - aws ecr get-login-password | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
  pre_build:
    commands:
      - echo Pre-Build Phase `date`
      - cat $CODEBUILD_SRC_DIR_SourceArtifactGit/schema/authzed-schema.yaml
      - cat imageDetail.json
      - sudo apt update
      - sudo apt-get install build-essential
      - sudo apt install git -y
      - /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - (echo; echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"') >> /home/$USER/.bashrc
      - eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
      - brew install authzed/tap/zed
  build:
    commands:
      - echo Build Phase `date`
      - zed validate $CODEBUILD_SRC_DIR_SourceArtifactGit/schema/authzed-schema.yaml
      - zed import $CODEBUILD_SRC_DIR_SourceArtifactGit/schema/authzed-schema.yaml --endpoint ip-10-0-2-59.ec2.internal:50051 --token test --insecure
      - docker pull 481543810001.dkr.ecr.us-east-1.amazonaws.com/cardata-micro-data-authz:latest
  post_build:
    commands:
      - echo Post-Build Phase `date`
      - docker run --entrypoint "spicedb" 481543810001.dkr.ecr.us-east-1.amazonaws.com/cardata-micro-data-authz:latest migrate head --datastore-engine=postgres --datastore-conn-uri="postgres://postgres:password@ec2-54-225-181-18.compute-1.amazonaws.com:5432/spicedb?sslmode=disable"
artifacts:
  files:
    - $CODEBUILD_SRC_DIR_SourceArtifactGit/schema/authzed-schema.yaml
  discard-paths: yes