version: 0.2
proxy:
  upload-artifacts: no
  logs: no
phases:
  install:
    runtime-versions:
      golang: 1.20
    commands:
      - $(aws ecr get-login --region ${AWS_REGION} --no-include-email)
  pre_build:
    commands:
      - echo Pre-Build Phase `date`
  build:
    commands:
      - echo Build Phase `date`
      - docker build -t $REPO_NAME:$VERSION .
  post_build:
    commands:
      - echo Post-Build Phase `date`
      - docker tag $REPO_NAME:$VERSION $REPO_URL/$REPO_NAME:$VERSION
      - docker push $REPO_URL/$REPO_NAME:$VERSION
      - printf '{"Version":"%s"}' $VERSION > Overrides.json
artifacts:
  files:
    - Overrides.json
    - cloudformation/*
  discard-paths: yes