version: 0.2
proxy:
  upload-artifacts: no
  logs: no
phases:
  install:
    runtime-versions:
      golang: 1.20
    commands:
      - aws ecr get-login-password | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
  pre_build:
    commands:
      - echo Pre-Build Phase `date`
      - cat $CODEBUILD_SRC_DIR_SourceArtifactGit/Dockerfile
      - cat imageDetail.json
  build:
    commands:
      - echo Build Phase `date`
      - docker pull 481543810001.dkr.ecr.us-east-1.amazonaws.com/cardata-micro-data-authz:latest
  post_build:
    commands:
      - echo Post-Build Phase `date`
      - docker run --rm -p 50051:50051 authzed/spicedb migrate head --datastore-engine=postgres --datastore-conn-uri="postgres://postgres:password@ec2-54-225-181-18.compute-1.amazonaws.com:5432/spicedb?sslmode=disable" --grpc-preshared-key "test"
artifacts:
  files:
    - Overrides.json
    - cloudformation/*
  discard-paths: yes