Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: my-vpc

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: us-east-1a
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: my-public-subnet

  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: us-east-1b
      MapPublicIpOnLaunch: false
      Tags:
        - Key: Name
          Value: my-private-subnet

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: my-internet-gateway

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: my-public-route-table

  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: my-private-route-table

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PrivateRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NATGateway

  EIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  NATGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      SubnetId: !Ref PublicSubnet
      AllocationId: !GetAtt EIP.AllocationId
      Tags:
        - Key: Name
          Value: my-nat-gateway

  PublicSubnetAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref PublicRouteTable

  PrivateSubnetAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet
      RouteTableId: !Ref PrivateRouteTable

  CodeBuildSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: codebuild-sg
      GroupDescription: Security group for CodeBuild
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0

  ECSCluster:
    Type: 'AWS::ECS::Cluster'
    Properties:
      ClusterName: develop
      CapacityProviders:
        - FARGATE
        - FARGATE_SPOT
      ClusterSettings:
        - Name: containerInsights
          Value: enabled
      Configuration:
        ExecuteCommandConfiguration:
          Logging: DEFAULT
      ServiceConnectDefaults:
        Namespace: develop
      Tags:
        - Key: project
          Value: project1
  LogsDestinationParameter:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Name: LogsDestination
      Type: String
      Value: ecs
      Description: Event Log Destination

  LogRetentionInDaysParameter:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Name: LogRetentionInDays
      Type: String
      Value: 30
      Description: LogRetentionInDays

  ServiceMinCountParameter:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Name: ServiceMinCount
      Type: String
      Value: 2
      Description: ServiceMinCount

  ServiceMaxCountParameter:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Name: ServiceMaxCount
      Type: String
      Value: 10
      Description: ServiceMaxCount

  MinimumHealthyPercentParameter:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Name: MinimumHealthyPercent
      Type: String
      Value: 50
      Description: MinimumHealthyPercent

  MaximumPercentParameter:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Name: MaximumPercent
      Type: String
      Value: 100
      Description: MaximumPercent

Outputs:
  VpcId:
    Value: !Ref VPC
    Export:
      Name: VpcId
  PublicSubnetId:
    Value: !Ref PublicSubnet
    Export:
      Name: PublicSubnetId
  PrivateSubnetId:
    Value: !Ref PrivateSubnet
    Export:
      Name: PrivateSubnetId
  EIPAllocationId:
    Value: !GetAtt EIP.AllocationId
  CodeBuildSecurityGroupId:
    Value: !Ref CodeBuildSecurityGroup
    Export:
      Name: CodeBuildSecurityGroupId
  ECSCluster:
    Description: The created cluster.
    Value: !Ref ECSCluster
    Export:
      Name: ECSDevelopCluster